name: Deploy to Server

on:
  push:
    branches:
      - main # 在推送到主分支时触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no username@your_server_ip "
            cd /path/to/your/project &&
            git pull origin main &&
            npm install &&
            npm run build &&
            sudo systemctl restart nginx
          "
