name: Deploy Vue 3 Project to Linux Server

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出最新代码

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # 使用 GitHub Secrets 中的私钥

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@110.42.33.228 "
          cd /data/frontend/webgis_srtp && git pull origin main && ./deploy_script.sh"
